echo Testing Backprop
(cd rodinia/julia_gen/backprop/; ./verify)
echo Testing BFS
(cd rodinia/julia_gen/bfs/; ./verify)
echo Testing Hotspot
(cd rodinia/julia_gen/hotspot/; ./verify)
echo Testing Leukocyte
(cd rodinia/julia_gen/leukocyte/; ./verify)
echo Testing LUD
(cd rodinia/julia_gen/lud/; ./verify)
echo Testing NN
(cd rodinia/julia_gen/nn/; ./verify)
echo Testing NW
(cd rodinia/julia_gen/nw/; ./verify)
echo Testing ParticleFilter
(cd rodinia/julia_gen/particlefilter/; ./verify)
echo Testing PathFinder
(cd rodinia/julia_gen/pathfinder/; ./verify)
echo Testing StreamCluster
(cd rodinia/julia_gen/streamcluster/; ./verify)
